# Default values for my-app.

nameOverride: ""
fullnameOverride: ""

runtimeClassName: "kata-qemu"

image:
  repository: nginx # CHANGE THIS to your app image
  pullPolicy: IfNotPresent
  tag: "latest5"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUAverageValue: "800m"
  # targetMemoryUtilizationPercentage: 80

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 2Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

podAnnotations:

ingress:
  enabled: true
  className: "nginx" # IMPORTANT: This connects to your existing Load Balancer
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: helm.zormal.com # CHANGE THIS to your desired domain
      paths:
        - path: /
          pathType: Prefix


